/* Eternal 求婚故事配置：女生第一人称、线性时间线、离线本地素材。 */
const CONFIG = {
  meta: {
    title: "我们的故事", heroName: "QzSama", heroineName: "可乐就是好喝",
    realHeroName: "赵启志", realHeroineName: "朱盈畅", proposalDate: "2025.05.20",
    endingLine: "Chapter 1 完 / 我们的故事，才刚刚开始",
    proposalCopy: "但是，\n他还想和你一起，创造更多美好的回忆。\nSo… Will you marry me?",
    endingTitle: "SHE SAID YES !!",
    endingSubtitle: "她说好！",
    endingContinuation: "つづく\n未完待续",
  },
  audio: {
    bgm: { opening: "", game: "", date: "", proposal: "" },
    sfx: { click: "synth:click", select: "synth:select", type: "synth:type", gunshot: "synth:gunshot", hit: "synth:hit", capture: "synth:capture", heartbeat: "synth:heartbeat", bell: "synth:bell", success: "synth:success" },
  },
  images: {
    backgrounds: {
      ow_menu: "assets/images/backgrounds/ow_menu.jpg", ow_route66: "assets/images/backgrounds/ow_route66.jpg",
      chat_night: "assets/images/backgrounds/chat_night.jpg", first_date: "assets/images/backgrounds/first_date.jpg",
      park: "assets/images/backgrounds/park.jpg", proposal: "assets/images/backgrounds/proposal.jpg",
    },
    characters: {
      hero: { neutral: "assets/images/characters/hero_neutral.jpg", smile: "assets/images/characters/hero_smile.jpg", serious: "assets/images/characters/hero_serious.jpg" },
      heroine: { normal: "assets/images/characters/heroine_normal.jpg", laugh: "assets/images/characters/heroine_laugh.jpg", shy: "assets/images/characters/heroine_shy.jpg" },
    },
    photos: ["assets/images/photos/photo1.jpg", "assets/images/photos/photo2.jpg", "assets/images/photos/photo3.jpg", "assets/images/photos/photo4.jpg"],
    minigame: { kiriko: "assets/images/minigame/player.jpg", moira: "assets/images/minigame/healer.jpg" },
  },
  minigame: { duration: 45, kirikoHP: 100, kirikoInitialHP: 35, orbSpawnInterval: 1100, orbSpeed: 4.2, orbLife: 600, purpleDamage: 3, arenaPadding: 40 },
  memoryBubbleInterval: 3500,
  memoryBubbles: [
    { photo: "photo1", meta: "守望先锋线下展览 / 第一次约出去", caption: "第一次约出去见面，我其实紧张了很久。" },
    { photo: "photo2", meta: "演唱会重放", caption: "我们并肩坐着，分享同一段旋律。" },
    { photo: "photo3", meta: "脱口秀", caption: "笑到停不下来时，我发现自己已经习惯看向你。" },
    { photo: "photo4", meta: "X118 / 好吃的 / 漫长散步", caption: "逛动漫商场、到处吃好吃的，平凡的日子也变成了约会。" },
  ],
  story: {
    start: [
      { scene: { bg: "ow_menu", effect: "fade" } }, { bgm: { track: "opening", fade: 1500 } },
      { say: { who: "narration", text: "我是朱盈畅。故事的开始，不是在游戏里，而是在小红书的一篇笔记上。" } },
      { say: { who: "narration", text: "我写下「大龄游戏宅, 喜欢玩OW」，没想到有人在下面留言：「戳戳,🙋‍♀️」。" } },
      { say: { who: "narration", text: "他很快发来组队邀请。那天晚上，我们第一次在语音里听见彼此的声音。" } },
      { say: { who: "narration", text: "从那以后，我和他就这样认识了。" } }, { jump: { label: "relationship" } },
    ],
    relationship: [
      { scene: { bg: "chat_night", effect: "fade" } },
      { say: { who: "narration", text: "我主玩雾子，他主玩莫伊拉。每晚组局，成了我最期待的时间。" } },
      { show: { char: "hero", pos: "left", expr: "smile" } }, { show: { char: "heroine", pos: "right", expr: "normal" } },
      { say: { who: "hero", expr: "smile", text: "这波紫球丢过去，肯定能收割！" } },
      { say: { who: "narration", text: "紫球在我身边弹开，我的血量一点点见底。他却还盯着前方。" } },
      { say: { who: "heroine", expr: "laugh", text: "我没事，你先玩开心。" } },
      { say: { who: "narration", text: "我没有责怪他。看着他认真又有点笨拙的样子，我反而觉得很安心。" } },
      { say: { who: "hero", expr: "serious", text: "除了组局，我也想单独和你说说话。" } },
      { say: { who: "narration", text: "那句话之后，我们决定约出去见面。" } },
      { scene: { bg: "ow_route66", effect: "fade" } }, { bgm: { track: "game", fade: 1000 } },
      { say: { who: "narration", text: "在见面以前，我们先玩了一局特别的训练：我在莫伊拉身后残血等待。" } },
      { call: { minigame: "default" } },
      { say: { who: "narration", text: "我按下 X，说出「我需要治疗」。所有紫球变成了黄球，终于蹭到我身上，把血量奶满。" } },
      { say: { who: "narration", text: "那一刻我想，也许我们真的可以一直这样互相照顾。" } }, { jump: { label: "dates" } },
    ],
    dates: [
      { scene: { bg: "first_date", effect: "fade" } }, { bgm: { track: "date", fade: 1500 } },
      { say: { who: "narration", text: "第一次见面，我们去了守望先锋线下展览和活动。屏幕里的队友，终于变成了身边的人。" } },
      { say: { who: "narration", text: "后来我们一起看演唱会重放、看脱口秀，也到处寻找好吃的店。" } },
      { say: { who: "narration", text: "我们去 X118 逛动漫商场，挑喜欢的周边，聊到商场快要关门。" } },
      { show: { char: "heroine", pos: "center", expr: "shy" } },
      { say: { who: "narration", text: "一次又一次的见面里，我发现自己会在他笑的时候跟着笑，也会在分别时偷偷期待下一次。" } },
      { say: { who: "narration", text: "喜欢不是突然发生的。它藏在每一顿饭、每一场演出和每一段一起等待的路上，慢慢长大。" } }, { jump: { label: "confession" } },
    ],
    confession: [
      { scene: { bg: "park", effect: "fade" } },
      { say: { who: "narration", text: "2025年5月20日，他约我吃饭。饭后，他从身后拿出一束花。" } },
      { show: { char: "hero", pos: "left", expr: "serious" } }, { show: { char: "heroine", pos: "right", expr: "shy" } },
      { say: { who: "hero", name: "赵启志", text: "朱盈畅，我喜欢你。愿意和我正式在一起吗？" } },
      { say: { who: "narration", text: "我收下了花，也收下了这份认真。那天，我们正式在一起。" } },
      { say: { who: "narration", text: "我们一起看了电影《情书》。后来又去了好多地方，看了好多场演唱会，创造了很多有意义、很开心的回忆。" } }, { jump: { label: "memories" } },
    ],
    memories: [{ memory: {} }],
    proposal: [
      { scene: { bg: "proposal", effect: "zoomin" } }, { hide: { char: "*" } }, { bgm: { track: "proposal", fade: 2000 } },
      { effect: { type: "spotlight" } },
      { show: { char: "hero", pos: "left", expr: "serious" } },
      { proposal: {} },
    ],
  },
};
